FROM adoptopenjdk/openjdk11:ubi
RUN mkdir /opt/app
COPY /var/lib/jenkins/workspace/DevEnv/integrated-cart/integratedCartService/build/libs/integratedCartService.jar /opt/app
CMD ["java", "SPRING_PROFILES_ACTIVE=cloud", "-jar", "/opt/app/integratedCartService.jar"]
